### ISSUE TITLE
Export files all have same max size?

### ISSUE THREAD

**Issue by brundles** [gitlab-ce-export-to-csv/gitlab-ce-export-to-csv.github.io#1]
First off, **thank you** for this incredibly useful tool - its super!

Second, i have an issue. When i select a group, and then download the issues, the file always reach a max size of roughly 24 kb.

Perhaps i think you also need to enclose each part with "" so it is not some_title, some_description but "some_title", "some_description" to ensure the output can work with Excel :)

**Comment by brundles** [comment]
Nothing on this? :-/

**Comment by natanielpaiva** [comment]
Thanks!
You are using Google Chrome? I using Linux and for extract informations i use Google Sheets.
My file csv are exported with 302 kb...
View my video:
https://www.youtube.com/watch?v=xoeT2bg7hYk&t=324s

I go done your suggestion, but in 2018-05-22 due personal problems...

**Comment by natanielpaiva** [comment]
I did not find the problem @brundles
